### PR TITLE
Remove import error

### LINKED ISSUE #1901: pylint config: enable "import-error"
We enabled pylint in the project, however several code style violations already exist. There's no point in enabling rules and then not enforcing them, therefore any rule that is not already enforced is currently disabled.

One of these rules if _the one you can see in the title is this issue_.

**How to solve**
Create a pull request with 2 commits. The commits should:

1. Enable the rule in pylintrc ([see this commit for an example](https://github.com/kantord/LibreLingo/pull/1895/commits/d4c873224d1ad11710034a955c1dbfbe617c9d19))
2. Make sure that the CI still passes after creating your pull requests. If the CI fails due to the violations of the rule you've just enabled, then fix the code style mistake in the code and create a new commit. ([see this commit for an example](https://github.com/kantord/LibreLingo/pull/1895/commits/389969a5f5e3452cf9dbe35c0848e44a552ed544))

Take a look at this MR to see how your pull request should look: https://github.com/kantord/LibreLingo/pull/1895

Another (bigger) example of a similar pull request: https://github.com/kantord/LibreLingo/pull/1893

An example of how to write your commit messages:

**Why solve like this**
I have considered keeping the rules enabled but allowing the CI to pass with a certain number of pylint rule violations. I don't like this approach though, because it results in a very long and polluted output in pylint, which would render the output unusable for practical purposes.

**Additional context**
This is a good first issue because it will likely take little time to fix, and it does not require knowledge of LibreLingo or the project structure. It also does not require you to be an expert in 

Some things you might find useful:

- How to set up the project locally: https://librelingo.app/docs/#setting-up-the-development-environment
- How to run pylint locally: `poetry run pylint $(git ls-files '*.py')`
- How to fix code style issues with `black`. This can be useful to fix indentation after you changed the code: `poetry run black apps`
- Where we store our pylint config: https://github.com/kantord/LibreLingo/blob/main/pylintrc

### PR DESCRIPTION
**Pull request by dushyantbhardwaj9**
## Description

Removed import-error from pylintrc and completed recommended changes in the code.

**Is this related to any open issue(s)?**

fixes #1901

_..._

## Checklist

Don't worry if you haven't done everything on this checklist. Simply create your PR, and make sure everything is done later,
or ask for help if you don't know how to do it.

- [ ] The CI is passing
- [x] I tested my implementation manually
- [ ] I wrote new tests to test my code, or updated existing tests to test my changes

### CODE REVIEW

**Comment by kantord** [comment]
hi @dushyantbhardwaj9  looks like this makes mypy fail as it does not recognize the ignore type anymore :thinking:

**Comment by dushyantbhardwaj9** [comment]
I can't think of any reason why it shouldn't. How do I check for mypy?
I can try a few things (like replacing `;` with ` #` or moving `# type: ignore` to the end). I'll let you know, if anything work and update the code with it.  🙂

**Comment by kantord** [comment]
> How do I check for mypy?

```bash
poetry run mypy apps
```

**Comment by dushyantbhardwaj9** [comment]
I updated the comment with this `# type: ignore # pylint: disable=import-error`. But now it's throwing me some other error. I ran  `python3 -m pip install types-requests` this to install the types, but no change in the mypy error.

Below is the output of `poetry run mypy apps`.

```
apps/tools/generate.py:4: error: Library stubs not installed for "requests" (or incompatible with Python 3.8)
apps/tools/generate.py:4: note: Hint: "python3 -m pip install types-requests"
apps/tools/generate.py:4: note: (or run "mypy --install-types" to install all missing stub packages)
apps/tools/generate.py:4: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 40 source files)
```

**Comment by kantord** [comment]
> I updated the comment with this `# type: ignore # pylint: disable=import-error`. But now it's throwing me some other error. I ran `python3 -m pip install types-requests` this to install the types, but no change in the mypy error.
> 
> Below is the output of `poetry run mypy apps`.
> 
> ```
> apps/tools/generate.py:4: error: Library stubs not installed for "requests" (or incompatible with Python 3.8)
> apps/tools/generate.py:4: note: Hint: "python3 -m pip install types-requests"
> apps/tools/generate.py:4: note: (or run "mypy --install-types" to install all missing stub packages)
> apps/tools/generate.py:4: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
> Found 1 error in 1 file (checked 40 source files)
> ```

`python3 -m pip install types-requests` is not how it should be installed because we use poetry which manages virtualenvs in a different way. Maybe even that command should work at least locally (I'm not sure) but to make it reproducible on other people's computer you should install it like this:


```bash
poetry add --dev types-requests
```

**Comment by kantord** [comment]
> I updated the comment with this `# type: ignore # pylint: disable=import-error`. But now it's throwing me some other error. I ran `python3 -m pip install types-requests` this to install the types, but no change in the mypy error.
> 
> Below is the output of `poetry run mypy apps`.
> 
> ```
> apps/tools/generate.py:4: error: Library stubs not installed for "requests" (or incompatible with Python 3.8)
> apps/tools/generate.py:4: note: Hint: "python3 -m pip install types-requests"
> apps/tools/generate.py:4: note: (or run "mypy --install-types" to install all missing stub packages)
> apps/tools/generate.py:4: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
> Found 1 error in 1 file (checked 40 source files)
> ```

in any case, looks like this is not your fault. Looks like the `main` branch was probably broken when this happened. I mean, the errors are not happening in the files that you've modified. This problem should go away immediately if you rebase your branch or merge `main` into it

**Comment by kantord** [comment]
In any case, with the current version of the code on your branch, this is the failure I see in the pipeline still:

2022-01-11T09:25:13+01:00

**Comment by dushyantbhardwaj9** [comment]
That error message was after I made the change. After adding types, there are no more errors. I'll rebase and create a PR or you can replace ';' to ' #'. And mypy will stop bothering you about this 😊

image

**Comment by kantord** [comment]
Thanks @dushyantbhardwaj9 it works now!

@allcontributors please add @dushyantbhardwaj9 for code

**Pull request merged**
