### PR TITLE
Initial german-from-english course based on the french-from-english c…

### PR DESCRIPTION
**Pull request by myxor**
## Description

Initial version of german-from-english course based on the french-from-english course

**Is there anything you need help with to get this PR merged?**

i did **not yet change the UUID** from the french-from-english course so this still has to be done.

## Checklist

Don't worry if you haven't done everything on this checklist. Simply create your PR, and make sure everything is done later,
or ask for help if you don't know how to do it.

- [ ] The CI is passing
- [ ] I tested my implementation manually
- [ ] I wrote new tests to test my code, or updated existing tests to test my changes

### CODE REVIEW

**Comment by kantord** [comment]
hi @myxor 

amazing!

> i did not yet change the UUID from the french-from-english course so this still has to be done.

can you please change the UUID? then I'll merge it and export it so that you can see it in production (sorry, no easier way to preview a course yet :see_no_evil: )

**Comment by myxor** [comment]
> can you please change the UUID?

done.

> then I'll merge it and export it so that you can see it in production (sorry, no easier way to preview a course yet see_no_evil )

yeah i noticed that :)

Well, this contribution is obviously just a very basic one but maybe people that speak German will start contributing :)

**Comment by kantord** [comment]
one last thing, maybe you could use the latest version of the license? https://creativecommons.org/licenses/by/4.0/

**Comment by myxor** [comment]
> one last thing, maybe you could use the latest version of the license? https://creativecommons.org/licenses/by/4.0/

Done.

**Comment by myxor** [comment]
I updated the coursed README as well

**Comment by kantord** [comment]
@allcontributors please add @myxor for content

**Comment by kantord** [comment]
Thank you, @myxor !

**Comment by kantord** [comment]
Cool, @myxor  you should be able to preview it here: https://librelingo.app/course/german-from-english/

**Pull request merged**
