### PR TITLE
feat: modified typo message to make more noticable

### PR DESCRIPTION
**Pull request by kylemumma**
solved issue #82

### CODE REVIEW

**Comment by kantord** [comment]
Your tests seem to be failing. Looks like you need to update your jest tests

**Comment by kantord** [comment]
Cypress tests are failing. It's because the[ feature files](https://github.com/kantord/LibreLingo/tree/master/workspaces/web/cypress/integration) are outdated on your branch

**Comment by kylemumma** [comment]
@kantord thanks for the feedback, i'll get that fixed. Is there any way to run the tests before I make the pull request to make sure everything is working?

**Comment by kantord** [comment]
> Is there any way to run the tests before I make the pull request to make sure everything is working?

yes.

- `yarn jest` - runs jest based tests
- `yarn web cy:run` runs the end to end tests

Additionally, `yarn web cy:open` will give you an interactive interface for the end-to-end tests, if you want to see what's happening!

**Comment by kantord** [comment]
Hi! Looks good to me!

But would you maybe consider adding some more visual changes? For example, choosing a different color? Or highlighting the correct spelling with a different color? I think some people would still consider that it's not obvious enough that a typo has been made.

Other than that looks perfect

**Comment by kylemumma** [comment]
@kantord thought i'd update you on what i've been up to... i've been working on the following changes, let me know what you think:

- changing the background color for a typo to $yellow

- adding the option to send messageDetail as an array, such that each element in the array is one detail, this will enable the option to have multiline messageDetail so when you have a typo you can not only see the correct spelling but also what it translates to (trying to think of a good way to style this bc at the moment it looks a little cluttered)

- adding underlining to each word you misspelled (quickest algorithm i've thought up is comparing each word one by one, of submitted vs correct... not sure if there's a quicker way)

**Comment by kantord** [comment]
Hi :wave:  @kylemumma! Amazing!!

If you feel like, you can do this in this PR:
- changing the background color for a typo to $yellow

If it looks good, that's the only change needed for this MR before I can merge it! :100: 

Afterwards, the other things that you've suggested, you can do in 2 separate PRs:
- adding the option to send messageDetail as an array, such that each element in the array is one detail, this will enable the option to have multiline messageDetail so when you have a typo you can not only see the correct spelling but also what it translates to (trying to think of a good way to style this bc at the moment it looks a little cluttered)
- adding underlining to each word you misspelled (quickest algorithm i've thought up is comparing each word one by one, of submitted vs correct... not sure if there's a quicker way)

**Comment by kantord** [comment]
BTW, @kylemumma, for finding the misspelled words, maybe you could consider using `diffWords` from https://github.com/kpdecker/jsdiff

**Comment by kylemumma** [comment]
here is what the new typo challenge panel looks like from this PR:
tmp

**Review by kantord — APPROVED** [review]
:100:

**Comment by kantord** [comment]
Amazing, @kylemumma! Thank you so much

@allcontributors please add @kylemumma for code

**Comment by kantord** [comment]
If you are still working on the 2 extra features you mentioned: feel free to create issues for them. I'll assign you.

**Pull request merged**
