### PR TITLE
Create FUNDING.yml

### PR DESCRIPTION
**Pull request by navanchauhan**
Just merge this and enable the button by going to
 Settings>Options>Features>Check the Sponsorship Button

### CODE REVIEW

**Comment by navanchauhan** [comment]
Closes #19

**Comment by kantord** [comment]
thanks!

**Comment by kantord** [comment]
@allcontributors add @navanchauhan for docs

**Comment by kantord** [comment]
I can't see the button yet though :thinking: maybe it just takes time for it to appear?

**Comment by navanchauhan** [comment]
Have you enabled it from settings?

**Comment by kantord** [comment]
:+1:

**Pull request merged**
