### PR TITLE
feat: add finish early button

### PR DESCRIPTION
**Pull request by jobedylbas**
This PR resolves the issue #734 , I follow the issue comments and put as the features below:

- [ X ] Ultimate SKIP (Skipping all remaining challenges);
- [ X ] takes the user back to the course screen;
- [ X ] should appear after the first successful answer;
- [ X ] The button could say sth like Finish early.

I hope that helps. Please, test and let me know if I did something wrong.

Also, can you add the topic "hacktoberfest" on this repository?

Thank you, have a great Hacktoberfest and stay safe. 🧑‍💻

### CODE REVIEW

**Comment by kantord** [comment]
> Also, can you add the topic "hacktoberfest" on this repository?

sure thing! just did

**Comment by kantord** [comment]
Thanks!!!! It looks amazing. The code makes sense too.

Two things:

- can you please rebase your branch to current master
- do you think that "Finish early" should maybe lead to the success page too? Or a version of it? I think it would be still useful to congratulate he user :-)

**Comment by jobedylbas** [comment]
Pretty sure

I'm already done the following requests:

- [ X ] Rebase to the current master;
- [ X ] Lead the user to the success page.

I believe that is pretty awesome right now. 😊

**Comment by kantord** [comment]
Looks perfect!

**Review by kantord — APPROVED** [review]
:100:

**Comment by kantord** [comment]
@allcontributors please add @jobedylbas for code

**Pull request merged**
