### PR TITLE
feat: new design

### PR DESCRIPTION
**Pull request by kivutar**
Use bright colors and gamy buttons and font.

#618

### CODE REVIEW

**Comment by doamatto** [comment]
Since this is a WIP, consider [switching this PR to a draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

**Comment by kantord** [comment]
This is amazing @kivutar thank you so much!!

**Comment by kantord** [comment]
Screenshot_2020-08-23 LibreLingo

I would say that this purple color in this amount is rather harsh on the eye. I think we need to either change the color, or adjust the design somehow.

The same applies to the loading screen, as well as these screens:

Screenshot_2020-08-23 LibreLingo(1)

Screenshot_2020-08-23 LibreLingo(2)

**Comment by kantord** [comment]
Screenshot_2020-08-23 LibreLingo(3)

It looks like not all buttons have the same kind of design. URL: https://libre-lingo-git-fork-kivutar-kivutar-newdesign.kantord.vercel.app/development

**Comment by kantord** [comment]
Screenshot_2020-08-23 LibreLingo(4)

these buttons are also weird

**Comment by kantord** [comment]
Screenshot_2020-08-23 LibreLingo(5)

the labels seems to be a little bit off

**Comment by kantord** [comment]
Screenshot_2020-08-23 LibreLingo(6)

I think this purple on white does not have enough contrast, it gets difficult for me to read in large blocks of text:

Screenshot_2020-08-23 LibreLingo(7)

**Comment by kantord** [comment]
Screenshot_2020-08-23 LibreLingo(8)

I would avoid purple text in general, at least on this white background. It's a bit hard on the eyes

**Comment by kantord** [comment]
Screenshot_2020-08-23 LibreLingo(9)

there's a new bug introduced: there should be only 3 cards here. 4 is for mobile

**Comment by slesingerm** [comment]
I'm a big fan of the gamy design idea! I've gone through the preview and a lesson and my general observations are:
- the purple used is a fun color, but after a while of reading the text I felt like I was on my way to a headache - I would change this to a darker purple for the text, or avoid using color in text and instead use the purple only for some features - the top bar, the buttons, the shading when you pick an answer
- I think I would prefer a font type that is "wider" and possibly bolder for the text to pop and be easier to read

**Comment by slesingerm** [comment]
I've also noticed the text in the "Preferences" card spills over to the next line:
Screenshot from 2020-08-23 20-28-42

**Comment by doamatto** [comment]
Addresing @slesingerm's issue with the purple being too bright:
  \> I was thinking a colour like `#7F4FBA` might be a good alternative
Addresing @slesingerm's idea to make fonts thicker and wider:
  \> I personally think the way it is looks nice, however some headers may need to be shrunk to accomodate the new (?) font
Addressing @kantord's concerns of purple text on a white background not looking right and not having enough contrast:
  \> As shown [here](https://webaim.org/resources/contrastchecker/?fcolor=ADA1E3&bcolor=FFFFFF), the contrast is not compliant at all. I would recommend keeping at black on white or use some grays to discerne things such as sub-text.
Addressing @kantord's concerns of "weird" looking buttons:
  \> I have to agree as none of the buttons follow a simple and conformed design philosophy. Some are boxy, while others are pill-shaped. Some have borders, while others don't. I think we need to establish a design style to keep conformity and ensure the site doesn't have mismatched styles

**Comment by doamatto** [comment]
This PR resolves #613 and #613.

**Comment by doamatto** [comment]
I did up some general styling in Figma to start to develop a common design style.
image


cc: @kivutar @kantord, I can add you both to the Figma file if you'd like. [Send me](https://doamatto.xyz/contact) the email you use for Figma and I'll send it over when I get a chance

**Comment by kantord** [comment]
> I did up some general styling in Figma to start to develop a common design style.
> image
> 
> cc: @kivutar @kantord, I can add you both to the Figma file if you'd like. [Send me](https://doamatto.xyz/contact) the email you use for Figma and I'll send it over when I get a chance

Thanks @doamatto! Can you maybe think of a way of sharing it with the entire community?

**Comment by kivutar** [comment]
There is this tool if you want to change the palette while keeping it consistent https://tailwind.ink/

**Comment by kantord** [comment]
Is there a way to perhaps split this up into multiple stages? So that we could already merge some of it, without having to do everything in one step.

**Comment by doamatto** [comment]
I don't see why not. We'd want to establish a design standard first and foremost.though so that everything is consistent.

19 Sep 2020, 10:27 by notifications@github.com:

**Pull request closed without merging**
