### PR TITLE
Add first Middle Persian lesson

### PR DESCRIPTION
**Pull request by aerabi**
## Description

Add a new course for Middle Persian, aka Parsig or Pahlavi.

## Checklist

Don't worry if you haven't done everything on this checklist. Simply create your PR, and make sure everything is done later,
or ask for help if you don't know how to do it.

- [ ] The CI is passing
- [x] I tested my implementation manually
- [ ] I wrote new tests to test my code, or updated existing tests to test my changes

### CODE REVIEW

**Comment by kantord** [comment]
Hi @aerabi :wave: Thank you!!! :tada:  This is amazing

**Comment by kantord** [comment]
@allcontributors please add @aerabi  for content

**Comment by aerabi** [comment]
> Hi @aerabi  Thank you!!!  This is amazing

Thanks a lot for your support, @kantord. I just don't understand why the CI fails. :thinking:

**Comment by kantord** [comment]
@aerabi I don't know either why the CI fails, I'll look into it.

Btw you can preview the current state of your course here :-) https://librelingo.app/course/parsig-from-english/

**Pull request merged**
