### PR TITLE
Added build and preview using Zeit Now

### PR DESCRIPTION
**Pull request by navanchauhan**
References issue #74 

@kantord 

In `now.json` change the name to something you like, I tested it on `librelingotest` so as to not block `librelingo`

Also you will need to add your ZEIT_TOKEN secret in the Repository's settings

### CODE REVIEW

**Comment by kantord** [comment]
Thank you so much for the pull request! I think it's authorized now, but the URLs still give 404. Also, is it possible to completely disable "production" deployment? We only need now.sh for staging

**Comment by navanchauhan** [comment]
I forgot to add the scope configuration 🤦‍♂

**Comment by kantord** [comment]
Still 404 :crying_cat_face:

**Comment by navanchauhan** [comment]
https://librelingo-three.now.sh/

It’s working on my repository, could you maybe try merging this to master and then making a dummy PR? If it still doesn’t work then you could roll back the commit

I have tested the code on my repo once more and it’s working 🤔

**Comment by kantord** [comment]
ok, let's try

**Comment by kantord** [comment]
@allcontributors please add @navanchauhan for infra

**Comment by kantord** [comment]
fixes #74

**Pull request merged**
