### PR TITLE
Add jest config to transpile tests, return tests

### PR DESCRIPTION
**Pull request by zinovik**
**Related issue**: https://github.com/kantord/LibreLingo/issues/790
**Related PR**: https://github.com/kantord/LibreLingo/pull/792

### CODE REVIEW

**Comment by zinovik** [comment]
```
yarn jestPassed in
yarn run v1.22.5
$ /home/semaphore/LibreLingo/node_modules/.bin/jest
PASS workspaces/web/src/db/skill/_logic.test.js
PASS workspaces/web/src/db/skill/getSkillStats.test.js
PASS workspaces/web/src/routes/course/[courseName]/skill/__tests__/logic.test.js
PASS workspaces/web/src/db/skill/__tests__/savePractice.test.js
PASS workspaces/web/src/__tests__/logic.test.js
PASS workspaces/answer-corrector/index.test.ts
PASS workspaces/web/src/components/ChipsChallenge/utils.test.js
PASS workspaces/web/src/db/db.test.js
​
File                                      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------------------------------|---------|----------|---------|---------|-------------------
All files                                 |   71.57 |    60.53 |   72.13 |   73.51 |                   
 answer-corrector                         |     100 |      100 |     100 |     100 |                   
  index.ts                                |     100 |      100 |     100 |     100 |                   
 web/src                                  |   93.75 |       60 |   66.67 |   93.75 |                   
  logic.js                                |      90 |       50 |   66.67 |      90 | 17                
  settings.js                             |     100 |    66.67 |     100 |     100 | 8-11              
 web/src/components/ChipsChallenge        |   85.71 |       50 |     100 |   85.71 |                   
  utils.js                                |   85.71 |       50 |     100 |   85.71 | 3                 
 web/src/db                               |   29.49 |    15.38 |   30.43 |   31.88 |                   
  db.js                                   |   24.66 |    15.38 |      20 |   27.69 | 28-29,39-162      
  getUserDbName.js                        |     100 |      100 |     100 |     100 |                   
 web/src/db/skill                         |   97.06 |    83.33 |     100 |     100 |                   
  _logic.js                               |     100 |      100 |     100 |     100 |                   
  getSkillStats.js                        |   92.86 |       75 |     100 |     100 | 4,18              
  savePractice.js                         |     100 |      100 |     100 |     100 |                   
 web/src/routes/course/[courseName]/skill |     100 |      100 |     100 |     100 |                   
  _logic.js                               |     100 |      100 |     100 |     100 |                   
------------------------------------------|---------|----------|---------|---------|-------------------
​
Test Suites: 8 passed, 8 total
Tests:       40 passed, 40 total
Snapshots:   0 total
Time:        6.486 s
Ran all test suites.
Done in 7.34s.
export SEMAPHORE_JOB_RESULT=passed
```

**Comment by kantord** [comment]
Hi, I like this, but there's already a `./workspaces/jest.config.js`, shouldn't you be overwriting/modifying that one instead? I think we don't need 2 jest.config.js files

**Comment by zinovik** [comment]
`./workspaces/jest.config.js` doesn't work. We can remove it, it changes nothing ;)

**Comment by zinovik** [comment]
I've removed it ;)

**Comment by kantord** [comment]
Amazing!!! Thank you @zinovik , and sorry for the slow response. I've been sick :thermometer: :sneezing_face:

**Comment by zinovik** [comment]
No problem ;)
Get well.

**Pull request merged**
