### PR TITLE
fix: do not display multiple of the same option in options challenges

### PR DESCRIPTION
**Pull request by zmbc**
Prevents the user from seeing multiple copies of the same option in an options challenge.

### CODE REVIEW

**Review by kantord — APPROVED** [review]

**Review by kantord — CHANGES_REQUESTED** [review]
Hi @zmbc, thanks for the contribution.

Looks like the eslint is failing: https://kantord.semaphoreci.com/jobs/586e351b-ca09-4c64-b629-40aaaf7b4b4d

Also, it looks like the Cypress tests might need some updating: https://kantord.semaphoreci.com/jobs/48cf3499-c5b0-419b-ac0d-3e0420668743

(Or maybe your change introduces some unintended side-effect?)

**Comment by zmbc** [comment]
@kantord Both issues should be resolved now.

By the way, this PR doesn't totally fix the problem, because it could still happen that an option is given that matches an *alternative* translation of the phrase/word. However, this info isn't even exported in the JSON yet so I have chosen not to tackle that here. Perhaps it makes sense to create an open issue to track this?

**Comment by kantord** [comment]
Thank you @zmbc ! 🏅

**Pull request merged**
