### PR TITLE
Setup Storybook

### PR DESCRIPTION
**Pull request by mooncakes-dev**
Setup Storybook under 'workspaces'.

Issue #237

### CODE REVIEW

**Comment by mooncakes-dev** [comment]
Not sure if you want me to resolve the yarn lock conflict without you checking them out. Let me know if you are okay with that

**Comment by kantord** [comment]
It would be nice if you could resolve the yarn.lock conflict. All you should need to do is rebase your branch and run `yarn install`. That will resolve the conflict automatically

**Comment by kantord** [comment]
Other than that, looks good to me!

**Comment by mooncakes-dev** [comment]
> It would be nice if you could resolve the yarn.lock conflict. All you should need to do is rebase your branch and run `yarn install`. That will resolve the conflict automatically

Hmm, it seems that rebase did not help, is it okay if I resolve it manually?

**Comment by kantord** [comment]
Are you sure you rebased to *my* master as opposed to yours? I think some other PR was merged, that updated dependencies.

It shouldn't really be resolved manually, because it's an automatically generated file :thinking: 

Here's some docs about syncing your fork's master to my master: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

let me know if you need help!

**Comment by mooncakes-dev** [comment]
You were correct, I was syncing it with my master and not yours! Thank you for bearing with me through this 🥰

**Comment by kantord** [comment]
Hi @mooncakes-dev, sorry for the slow reply. I've been sick, and not having much energy :sneezing_face: :face_with_thermometer: 

I am glad your problem got resolved! I think you might have forgotten to push your changes though! You will need to force-push probably. Also the semaphore CI checks are failing, but it looks like it's still about the lockfile issue

**Comment by mooncakes-dev** [comment]
Hi @kantord, I apologize for the delay, I got really sick for the past few weeks. 

I removed potential clashing dependencies, made sure that I was getting your main branch and our yarn locks are the same. I am struggling to undestand where the failed check is coming from 🤔

**Comment by kantord** [comment]
@mooncakes-dev please get well soon! Don't worry! 

The failed check seems to be coming from an issue with the yarn.lock file. Looks like there's also a conflict in the yarn.lock file. 

> Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.

This is the error message from the CI. This means that with the current version that's pushed to this PR, if you run `yarn install`, your `yarn.lock` file would change. This means that you haven't committed the latest version of your yarn.lock file.

The conflict in the yarn.lock file shouldn't worry you: if you just run `yarn install`, it will be updated. You just have to commit the automatically generated version and both the CI error and the conflict should be gone :rocket:

**Pull request closed without merging**
