### PR TITLE
fix: Updated svelte-i18n package to current version

### LINKED ISSUE #1661: Update svelte-i18n to v3.3.12
**Is your feature request related to a problem? Please describe.**
This could not be updated automatically due to failing CI. See original PR: https://github.com/kantord/LibreLingo/pull/1654

**Describe the solution you'd like**

- update to the latest version
- make sure the app still works properly and the CI passes

### PR DESCRIPTION
**Pull request by petercr**
## fix: This update fixes #1661 

I updated the `svelte-i18n` package to its most current version `3.3.13`.
There were breaking changes in how svelte-i18n called `init.initialLocale`, and some differences in how you imported each Language dictionary. 

These issues have been fixed in `apps/web/src/i18n.js` so it should work now. 

I had some trouble getting the CI to run locally on my machine 🤷‍♂️ 

**Is this related to any open issue(s)?**

fixes #1661 

**Is there anything you need help with to get this PR merged?**

Yes, if I could get some help with running the CI locally, that would be great 👌 
I can get the app running locally, but I can't get the tests to work.

## Checklist

Don't worry if you haven't done everything on this checklist. Simply create your PR, and make sure everything is done later,
or ask for help if you don't know how to do it.

- [ ] The CI is passing
- [ ] I tested my implementation manually
- [ ] I wrote new tests to test my code, or updated existing tests to test my changes

### CODE REVIEW

**Comment by petercr** [comment]
Here are the tests that are failing with the Semaphor CI build. 
* validate that the PyPi readme files are up to date
* validate that Test Course JSON files are up to date

It looks like all the Front End tests are passing though. 
I'm not sure how you would like me to proceed? 🤔

**Comment by kantord** [comment]
> Here are the tests that are failing with the Semaphor CI build.
> 
>     * validate that the PyPi readme files are up to date
> 
>     * validate that Test Course JSON files are up to date
> 
> 
> It looks like all the Front End tests are passing though. I'm not sure how you would like me to proceed? thinking
> 
> 

you are right @petercr 

let's try what happens

**Comment by kantord** [comment]
@allcontributors please add @petercr for code

**Pull request merged**
