### PR TITLE
Remove warnings from console

### LINKED ISSUE #798: Get rid of console warnings
**Describe the bug**
If you run the development server (`yarn web dev`), and run the Cypress tests,
(`yarn web cy:run`), you'll see that there are several console warnings.

**To Reproduce**

1. `yarn web dev`
2. `yarn web cy:run`

**Expected behavior**
There should be no console errors, the dev server output should be clean

**Screenshots**
2020-10-14-084744_571x529_scrot

### PR DESCRIPTION
**Pull request by vivek32ta**
Fixes #798  

Removed warnings from console when `yarn web dev` is run.
Thanks for letting me contribute :)

### CODE REVIEW

**Comment by kantord** [comment]
Hi, thanks! Can you please resolve the conflicts?

**Review by doamatto — APPROVED** [review]

**Comment by kantord** [comment]
Hi, @vivek32ta, looks like this change introduced a bug: https://percy.io/LibreLingo/LibreLingo/builds/7316175?utm_campaign=LibreLingo&utm_content=LibreLingo&utm_source=github_status_public

**Review by kantord — CHANGES_REQUESTED** [review]
If you rebase to master, you should be able to see the failures from Percy yourself.

These are bugs that are visual in aspect and are hard to notice/require you to have progress saved locally.

It will be easier to debug manually if you complete an exercise locally.

**Comment by kantord** [comment]
Hi @vivek32ta, how is it going? Do you need some help?

**Comment by vivek32ta** [comment]
Hey @kantord 

I'm so sorry for such a late reply. I've had to attend to an extreme family emergency.

I'm again extremely sorry that I won't be able to continue this one. 

Thank you for the opportunity.

**Comment by kantord** [comment]
@vivek32ta thanks for letting me know! I hope your family emergency will be resolved! :crossed_fingers:

**Comment by vivek32ta** [comment]
Thanks a lot for understanding @kantord.

**Pull request closed without merging**
