### PR TITLE
feat: click to select word

### LINKED ISSUE #759: Double clicking the words in sentence builder
**Is your feature request related to a problem? Please describe.**
With translate sentence, only drag&drop is available. To improve user experience I suggest adding double click.

**Describe the solution you'd like**
Double clicking : 
- adds the word at the end of the sentence
- removes the word from sentence into the word pool

**Additional context**
image

### PR DESCRIPTION
**Pull request by chickendude**
_Based off of  HugoLiconV's code. Removed sortable code and add onclick code._

## Description

I also changed the cursor when hovering over a button so the user knows to click.
It was a bit odd with the cursor never changing when using padding so i switched
to margin and increased the horizontal margin a bit as well.

**Is this related to any open issue(s)?**

Fixes #759

## Checklist

Don't worry if you haven't done everything on this checklist. Simply create your PR, and make sure everything is done later,
or ask for help if you don't know how to do it.

- [ ] The CI is passing
- [x] I tested my implementation manually
- [ ] I wrote new tests to test my code, or updated existing tests to test my changes

### CODE REVIEW

**Comment by kantord** [comment]
Thanks @chickendude, looks good to me!

Can you please resolve the conflicting file? Then I'll merge it

**Comment by kantord** [comment]
Looks like since you created your fork, `master` has been renamed to `main`, but your fork hasn't been updated. You probably have to [rename](https://github.com/github/renaming) it as well :thinking:  I think that's why the CI is not running.

**Comment by kantord** [comment]
Hi, I rebased and [merged](21655145760101942200042209) it for you on a separate branch to make it easier.

**Comment by kantord** [comment]
@allcontributors please add @chickendude for code!

**Comment by kantord** [comment]
@chickendude thanks a lot again for your contribution. Are you looking for more challenges in LibreLingo?

**Comment by chickendude** [comment]
@kantord Great thanks! Yeah i'd be happy to help out, i can definitely dedicate an afternoon or so a week to working on something, though i may need to spend some time learning how Svelte works first. I've spent more time on the Python/Django side of things but Svelte does seem interesting/worth knowing. I feel like i have a lot to learn from the way you've structured the project and the specific tools/libraries you're using.

**Comment by kantord** [comment]
Cool! Let me know I can help you with something. Also, if you have some feedback about the documentation/structure of the project, please let me know.

There's a plan to have a video call with people interested in LibreLingo. If you are interested, let's keep in touch on the chat: https://riot.im/app/#/room/#librelingo:matrix.org

**Pull request closed without merging**
